fx_version 'adamant'
games { 'gta5' };

client_scripts {
    "AlphaUI/RMenu.lua",
    "AlphaUI/menu/RageUI.lua",
    "AlphaUI/menu/Menu.lua",
    "AlphaUI/menu/MenuController.lua",
    "AlphaUI/components/Audio.lua",
    "AlphaUI/components/Enum.lua",
    "AlphaUI/components/Keys.lua",
    "AlphaUI/components/Rectangle.lua",
    "AlphaUI/components/Sprite.lua",
    "AlphaUI/components/Text.lua",
    "AlphaUI/components/Visual.lua",
    "AlphaUI/menu/elements/ItemsBadge.lua",
    "AlphaUI/menu/elements/ItemsColour.lua",
    "AlphaUI/menu/elements/PanelColour.lua",
    "AlphaUI/menu/items/UIButton.lua",
    "AlphaUI/menu/items/UICheckBox.lua",
    "AlphaUI/menu/items/UIList.lua",
    "AlphaUI/menu/items/UIProgress.lua",
    "AlphaUI/menu/items/UISeparator.lua",
    "AlphaUI/menu/items/UISlider.lua",
    "AlphaUI/menu/items/UISliderHeritage.lua",
    "AlphaUI/menu/items/UISliderProgress.lua",
    "AlphaUI/menu/panels/UIButtonPanel.lua",
    "AlphaUI/menu/panels/UIColourPanel.lua",
    "AlphaUI/menu/panels/UIGridPanel.lua",
    "AlphaUI/menu/panels/UIPercentagePanel.lua",
    "AlphaUI/menu/panels/UIStatisticsPanel.lua",
    "AlphaUI/menu/windows/UIHeritage.lua",
}

client_scripts {
    "lib/utils.lua",
    "config/*.lua",
    "client/*.lua",
    "client/*.lua",
    "client/menuUI/menu.lua",
    "client/menuUI/functions.lua",
}

server_scripts {
    "lib/utils.lua",
    "@mysql-async/lib/MySQL.lua",
    "config/*.lua",
    "server/*.lua",
    "server/player/*.lua",
    "server/menuUI/*.lua",
    "base.lua",
}

server_exports {
    "AddMoney",
    "RemoveMoney",
    "AddBank",
    "RemoveBank",
    "GetMoney",
    "GetBank",
    "HasEnoughBank",
    "HasEnoughCash",
    "BankToCash",
    "CashToBank",
    "CashTransfer",
    "BankTransfer",
    "AddItem",
    "RemoveItem",
    "AddItemIf",
    "ExhangeItem",
    "SavePlayerSkin",
    "SavePlayerIdentity",
    "DropItem",
    "CreatePickupItem",
    "SetItemArg",
    "RecruitPlayer",
    "LeaveJob",
    "ChangePlayerJobGrade",
    "BuyIfCan",
    "GetPlayerIdentity",
}

exports {
    "GetPlayerJob",
    "GetPlayerMoney",
    "GetPlayerBank",
    "GetPlayerInv",
    "IsPlayerLoaded",
    "GetPlayerUniqueId",
    "RegisterItemAction",
    "UseItem",
    "GetPlayerPermLevel",
    "GetPlayerIdentity",
    "GetPlayerJobGrade",
    "GetPlayerBossStatus",
    "GetPlayerSkin",
}